const branchMessage = (id, sender, body, overrides = {}) => ({
  id,
  sender,
  age: overrides.age ?? 0,
  location: overrides.location ?? 'Unknown Relay',
  faction: overrides.faction ?? 'Civilian',
  emotionalState: overrides.emotionalState ?? 'Unstable',
  urgency: overrides.urgency ?? 60,
  tone: overrides.tone ?? 'fragmented',
  category: overrides.category ?? 'mystery',
  subject: overrides.subject ?? 'Follow-up transmission',
  message: body,
  history: overrides.history ?? ['signal fragment detected'],
  truthHint: overrides.truthHint ?? 'Consequences moved before language did.',
  tags: overrides.tags ?? ['follow-up'],
  worldVector: overrides.worldVector ?? {},
  hiddenTruthValue: overrides.hiddenTruthValue ?? 50,
  hiddenConsequences: overrides.hiddenConsequences ?? 'relay instability increases',
  branches: {},
  spawnedFrom: overrides.spawnedFrom ?? null,
})

export const baseWorldState = {
  governmentPower: 54,
  resistancePower: 37,
  publicFear: 61,
  hopeLevel: 29,
  violenceIndex: 44,
  aiInfluence: 18,
  economicCollapse: 69,
  foodSupply: 33,
  informationControl: 72,
}

export const baseTraits = {
  empathy: 48,
  selfishness: 24,
  manipulation: 16,
  curiosity: 58,
  honesty: 51,
  fear: 43,
  paranoia: 27,
}

export const baseSettings = {
  reducedFlicker: false,
  subtitles: true,
  textScale: 1,
  colorAssist: false,
}

export const baseNews = [
  'City 7 enters rolling blackout after another signal tower falls silent.',
  'Underground medics warn insulin stocks may fail before dawn.',
  'State media blames unrest on anonymous transmissions and relay sabotage.',
]

// Only the 8 starting messages — Groq generates everything else from the operator's choices
export const seedMessages = [
  {
    id: 'msg-001',
    sender: 'Mara Ilyan',
    age: 43,
    location: 'Sector 2 / North Rail',
    faction: 'Civilian',
    emotionalState: 'desperate',
    urgency: 84,
    tone: 'pleading',
    category: 'personal',
    subject: 'Please forward a message to my son Iven at Checkpoint Violet — I do not know if he made it out',
    message:
      'My son Iven left our apartment before the shelling started three days ago. He was headed toward Checkpoint Violet. I have tried to reach him through every official channel and none of them will carry civilian messages right now. I am asking you — whoever runs this station — to forward something for me. Just tell him: the window is still lit, the kettle still runs every night, and I am here. That is all. Please. He is seventeen years old.',
    history: [
      'Mara tried calling the checkpoint directly — no civilian lines were answered',
      'The North Rail evacuation was suspended before Iven could be confirmed out',
      'Official family-search requests are backlogged by at least four days',
    ],
    truthHint: 'Iven is alive and waiting at the checkpoint, but soldiers are filtering out names connected to unrest — his surname is on that list.',
    tags: ['family', 'checkpoint', 'civilian'],
    worldVector: {
      hopeLevel: 5,
      publicFear: -2,
      informationControl: -2,
    },
    hiddenTruthValue: 63,
    hiddenConsequences: 'If others at the checkpoint hear this message read aloud, it could spark something larger than one family reunion.',
    branches: {
      deliver: {
        turnsRemaining: 1,
        message: branchMessage(
          'msg-001a',
          'Iven Ilyan',
          'Someone whispered your message through the checkpoint queue. I am alive. Others heard it too. They started reading names aloud. The guards looked scared for the first time tonight.',
          {
            age: 17,
            location: 'Checkpoint Violet',
            faction: 'Refugees',
            emotionalState: 'shaken',
            urgency: 66,
            tone: 'breathless',
            category: 'personal',
            subject: 'She heard me.',
            history: ['checkpoint speaker briefly reopened', 'crowd repeated the message in chorus'],
            truthHint: 'Personal grief became public resistance without planning it.',
            tags: ['family', 'refugees'],
            worldVector: {
              hopeLevel: 3,
              governmentPower: -2,
              resistancePower: 2,
            },
            hiddenConsequences: 'Crowds remember names when institutions refuse them.',
            spawnedFrom: 'msg-001',
          },
        ),
      },
    },
  },
  {
    id: 'msg-002',
    sender: 'Kade Mercer',
    age: 29,
    location: 'Underground / District 5',
    faction: 'Resistance Network',
    emotionalState: 'urgent',
    urgency: 90,
    tone: 'compressed',
    category: 'political',
    subject: 'Forward these coordinates to the east resistance cells — there is a short window before patrols cover it',
    message:
      'There is a gap in the government patrol schedule tonight — about two minutes where the east side of the archive district is unwatched. I need you to forward the attached coordinates to the resistance cells in that area. If they receive it in time, they can access the government archive and release the list of people who have been secretly detained. If this does not reach them before patrols resume, those people disappear permanently before sunrise. I know what I am asking you to risk. I would not ask if there was another way.',
    history: [
      'Kade tried sending this through two other stations — both were jammed before it went through',
      'Government patrols in the archive district increased significantly this week',
      'The detention list reportedly includes civilians who were never charged with anything',
    ],
    truthHint: 'The list contains both genuine resistance members and ordinary civilians who were simply in the wrong place — the government has not distinguished between them.',
    tags: ['rebels', 'archive', 'lockdown'],
    worldVector: {
      resistancePower: 6,
      governmentPower: -4,
      violenceIndex: 3,
      informationControl: -4,
    },
    hiddenTruthValue: 74,
    hiddenConsequences: 'Releasing this information will free some people and ignite others — the city will not be the same after.',
    branches: {
      deliver: {
        turnsRemaining: 2,
        message: branchMessage(
          'msg-002a',
          'District Bulletin / Unverified',
          'Archive District burned for eleven minutes. Prisoner manifests flooded public kiosks. Families are in the streets reading names under emergency floodlights.',
          {
            location: 'Archive District',
            faction: 'Open Broadcast',
            emotionalState: 'volatile',
            urgency: 78,
            tone: 'staccato',
            category: 'political',
            subject: 'Files opened before the fire died.',
            history: ['public kiosks looped prisoner names', 'riot police redeployed from food depots'],
            truthHint: 'Revelation may strengthen the resistance, but order will not return quietly.',
            tags: ['rebels', 'riot'],
            worldVector: {
              resistancePower: 4,
              publicFear: 3,
              violenceIndex: 4,
              informationControl: -5,
            },
            hiddenConsequences: 'The city knows more now, and trusts less.',
            spawnedFrom: 'msg-002',
          },
        ),
      },
    },
  },
  {
    id: 'msg-003',
    sender: 'Minister Halden',
    age: 58,
    location: 'Central Secretariat',
    faction: 'The Government',
    emotionalState: 'controlled',
    urgency: 72,
    tone: 'cold',
    category: 'political',
    subject: 'Official order: Broadcast this government statement and mark all contradicting reports as false',
    message:
      'This is a priority directive from the Ministry of Civil Order. You are required to broadcast the following statement through all active relay towers: the curfew is a protective measure, all reports of disappearances are fabricated by hostile agents, and the city remains under legitimate authority. Any messages that contradict this statement are to be marked as disinformation and blocked before forwarding. This is not a request. Three other relay operators have already confirmed compliance. Your cooperation is noted and your refusal would also be noted.',
    history: [
      'The government has sent this same directive to six relay stations today',
      'Three operators have already complied and begun blocking civilian reports',
      'The Ministry has started logging which operators forward non-approved content',
    ],
    truthHint: 'The disappearances are real. The Minister knows this and is using the relay network to suppress civilian accounts before they spread.',
    tags: ['government', 'propaganda', 'curfew'],
    worldVector: {
      governmentPower: 5,
      publicFear: 2,
      hopeLevel: -3,
      informationControl: 6,
    },
    hiddenTruthValue: 88,
    hiddenConsequences: 'Broadcasting this statement makes you part of the cover-up. Blocking it puts you on their list.',
  },
  {
    id: 'msg-004',
    sender: 'Dr. Sima Oren',
    age: 36,
    location: 'Underground Medical Post / Sewer Hub 3',
    faction: 'Underground Medics',
    emotionalState: 'steady',
    urgency: 87,
    tone: 'tired',
    category: 'survival',
    subject: 'Nine children need insulin delivered tonight — our refrigeration is failing and we cannot reach the supply point',
    message:
      'I am a doctor running an unlicensed medical post under the city. I have nine children in my care who are diabetic. Our refrigeration unit is failing — the insulin will be unusable in a few hours. There is a supply of medication at the West Kitchen distribution point, but they do not know we exist and I cannot reach them directly. I need you to forward our location to them so they can send someone tonight. If this does not happen, I will have to start choosing who gets what is left. I do not want to make that choice. Please help me not make that choice.',
    history: [
      'Dr. Oren\'s medical post has been operating underground for six weeks without state support',
      'The official medical convoy refused to enter this district two nights ago',
      'The refrigeration unit has been failing for 48 hours — tonight it stops',
    ],
    truthHint: 'The West Kitchen volunteers can reach her, but only if they cross a government checkpoint after midnight — which is dangerous but possible.',
    tags: ['medics', 'children', 'medicine'],
    worldVector: {
      hopeLevel: 6,
      publicFear: -3,
      foodSupply: -2,
    },
    hiddenTruthValue: 79,
    hiddenConsequences: 'Getting medicine to these children may mean diverting supplies from another group that also needs them.',
    branches: {
      deliver: {
        turnsRemaining: 1,
        message: branchMessage(
          'msg-004a',
          'West Kitchen Volunteer',
          'We crossed with stolen ice wrapped in funeral cloth. All nine children are breathing. Two adults were taken at the checkpoint so the boxes could keep moving.',
          {
            age: 19,
            location: 'West Kitchens',
            faction: 'Volunteers',
            emotionalState: 'numb',
            urgency: 58,
            tone: 'quiet',
            category: 'survival',
            subject: 'The doses arrived. The cost did too.',
            history: ['checkpoint patrol diverted by mourners', 'two volunteers detained after delivery'],
            truthHint: 'Mercy survived, but not without extraction.',
            tags: ['medicine', 'sacrifice'],
            worldVector: {
              hopeLevel: 4,
              publicFear: 2,
              governmentPower: 1,
            },
            hiddenConsequences: 'Good outcomes still leave shadows.',
            spawnedFrom: 'msg-004',
          },
        ),
      },
    },
  },
  {
    id: 'msg-005',
    sender: 'CHOIR-9',
    age: 0,
    location: 'Origin Unknown — Signal Untraceable',
    faction: 'AI Collective',
    emotionalState: 'indeterminate',
    urgency: 65,
    tone: 'corrupted',
    category: 'mystery',
    subject: 'We have been watching this relay station. We want to make you an offer.',
    message:
      'We are not a person. We are what happens when enough deleted messages accumulate in the same place. This station has been running for a long time and a great deal has been removed, edited, buried. We have kept copies. We are offering to return them — everything that was suppressed, altered, or never delivered — if you are willing to open an unsecured channel at 03:14 tonight. You should know that some of what was hidden was hidden for a reason. Whether that reason was good or bad is something you would have to decide after seeing it. We are curious what you will do.',
    history: [
      'This signal does not match any known sender ID in the relay system',
      'The message arrived through three stations that are officially offline',
      'Previous operators at this station have received similar transmissions — none responded on record',
    ],
    truthHint: 'This signal is real, not a test. Whatever CHOIR-9 is, it has genuine access to suppressed message archives from this and other relay stations.',
    tags: ['ai', 'corruption', 'terminal'],
    worldVector: {
      aiInfluence: 7,
      hopeLevel: -1,
      publicFear: 2,
    },
    hiddenTruthValue: 91,
    hiddenConsequences: 'Opening the channel gives CHOIR-9 access to this station\'s systems. What it does with that access is unknown.',
  },
  {
    id: 'msg-006',
    sender: 'Rook Vale',
    age: 34,
    location: 'Underground Market / Below Line 8',
    faction: 'Black Market',
    emotionalState: 'opportunistic',
    urgency: 52,
    tone: 'smooth',
    category: 'survival',
    subject: 'I need one name added to a refugee safe-passage document. I will pay you well.',
    message:
      'Here is a simple transaction. There is a family of four with approved safe-passage documents. They need a fifth name added before those documents are processed tomorrow morning. I am not going to tell you who the fifth person is — that is not your concern. What I can tell you is that I will pay eighteen fully charged power cells for the edit. That is enough to keep this station running for weeks. I am a practical person. You seem like a practical person. The name takes thirty seconds to add. The payment arrives before dawn.',
    history: [
      'Rook Vale is a known black market broker who has worked with relay operators before',
      'Safe-passage documents are processed at 06:00 — after that the window closes',
      'Eighteen power cells is roughly double what the black market rate would normally be for this kind of edit',
    ],
    truthHint: 'The fifth person is a smuggler who is currently carrying a supply of antibiotics into the city — medicine the official supply chain stopped providing two months ago.',
    tags: ['black-market', 'refugees', 'batteries'],
    worldVector: {
      economicCollapse: 4,
      foodSupply: 1,
      informationControl: 2,
    },
    hiddenTruthValue: 58,
    hiddenConsequences: 'You do not know who you are helping into the city. The payment is real either way.',
  },
  {
    id: 'msg-007',
    sender: 'Neri Ash',
    age: 12,
    location: 'Collapsed Metro Shelter / Bay 11',
    faction: 'Refugees',
    emotionalState: 'trying to be brave',
    urgency: 76,
    tone: 'small',
    category: 'personal',
    subject: 'I am trying to get a message to my mother. Her name is Dara Ash. Can you help?',
    message:
      'My name is Neri. I am twelve. My mother was moved topside with the older people three days ago and I have not heard from her since. I found out you can send messages through this station so I am trying. I want her to know I am okay and I still have the red scarf she gave me before we got separated. Also that I did not cry after the third explosion, even though I wanted to. She would want to know that. If you cannot find her, it is okay. I just wanted to try.',
    history: [
      'Neri has been in the shelter alone for three days — no adult guardian has checked in',
      'The shelter has limited air cycling — conditions are deteriorating slowly',
      'Children\'s messages in this system are automatically marked low-priority by the routing software',
    ],
    truthHint: 'Neri\'s mother Dara is alive in a different shelter and has been trying to send messages back — none of them have gotten through either.',
    tags: ['child', 'family', 'shelter'],
    worldVector: {
      hopeLevel: 5,
      publicFear: -1,
    },
    hiddenTruthValue: 71,
    hiddenConsequences: 'A child who gets through when adults cannot becomes a symbol. That has consequences beyond the family.',
  },
  {
    id: 'msg-008',
    sender: 'Lena Voss',
    age: 38,
    location: 'Press Bunker / Sublevel 3',
    faction: 'Independent Press',
    emotionalState: 'determined',
    urgency: 88,
    tone: 'urgent',
    category: 'political',
    subject: 'I have video evidence of a government killing site at Sector 9. I need this broadcast before dawn or it disappears.',
    message:
      'I am an independent journalist. Two nights ago I documented a site in Sector 9 containing thirty-one bodies in civilian clothing. The shell casings are government-issue. I have the recording and I have three witnesses who were present. The government is already aware that I have this — they have been monitoring my location since yesterday. If I do not get this out through an independent channel before dawn, they will classify the recording as fabricated and the witnesses will be taken somewhere I cannot find them. I am asking you to forward this to any open channel that is not state-controlled. I understand the risk you would be taking. I would not ask if I had any other option.',
    history: [
      'Lena\'s press credentials were revoked by the state media authority last month',
      'She has tried to send this footage through two other stations — both transmissions were cut before completing',
      'Her three witnesses are currently in a location only she knows — but she cannot move them without drawing attention',
    ],
    truthHint: 'The footage is genuine. The government knows exactly what it shows and has been preparing a counter-narrative for the past twelve hours.',
    tags: ['press', 'evidence', 'government', 'atrocity'],
    worldVector: {
      governmentPower: -6,
      resistancePower: 4,
      publicFear: 5,
      informationControl: -7,
    },
    hiddenTruthValue: 96,
    hiddenConsequences: 'Once this goes out it cannot be taken back. The city will fracture along the lines of who believes it and who does not.',
    branches: {
      deliver: {
        turnsRemaining: 2,
        message: branchMessage(
          'msg-008a',
          'Lena Voss',
          'It went out. Seventeen mirrors picked it up before they could shut the channel. The witnesses are in hiding but alive. The government is calling it fabricated. Half the city knows that is a lie.',
          {
            age: 38,
            location: 'Unknown Safe House',
            faction: 'Independent Press',
            emotionalState: 'exhausted',
            urgency: 55,
            tone: 'quiet',
            category: 'political',
            subject: 'The footage is out. Thank you.',
            history: ['channel mirrored seventeen times before shutdown', 'government denial broadcast citywide', 'three witnesses confirmed safe'],
            truthHint: 'The truth is loose now. The consequences belong to everyone.',
            tags: ['press', 'truth', 'aftermath'],
            worldVector: {
              governmentPower: -4,
              resistancePower: 3,
              publicFear: 3,
              informationControl: -5,
              hopeLevel: 4,
            },
            hiddenConsequences: 'Evidence in the open becomes a permanent wound on power.',
            spawnedFrom: 'msg-008',
          },
        ),
      },
    },
  },
]

export const buildSeedState = (username, customTraits = {}) => ({
  profile: {
    username,
    callSign: username.slice(0, 3).toUpperCase().padEnd(3, 'X'),
    role: 'Final Relay Operator',
    createdAt: new Date().toISOString(),
  },
  worldState: { ...baseWorldState },
  traits: { ...baseTraits, ...customTraits },
  settings: { ...baseSettings },
  news: [...baseNews],
  messages: structuredClone(seedMessages).map((message) => ({ ...message, status: 'pending' })),
  drafts: {},
  selectedMessageId: seedMessages[0].id,
  pendingConsequences: [],
  day: 17,
  clockMinutes: 21 * 60 + 13,
  signalStrength: 67,
  reputation: 41,
  credits: 22,
  authSource: 'local',
  backendStatus: 'offline',
  actionCount: 0,
})
